name = subpage
description = a sub-page of the homepage
template = subpage_theme

; ========================================
; Regions
; ========================================
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[highlighted] = Highlighted
regions[help] = Help
regions[content] = Content
regions[sidebar_first] = First Sidebar
regions[footer] = Footer

; ========================================
; Styles
; ========================================
stylesheets[all][] = css/layouts/sidebar/subpage_theme.layout.css 
stylesheets[all][] = css/layouts/sidebar/subpage_theme.layout.no-query.css