name = Home
description = This a a homepage layout for my first theme
template = home

; ========================================
; Regions
; ========================================
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[highlighted] = Highlighted
regions[help] = Help
regions[content] = Content
regions[sidebar_first] = First Sidebar
regions[footer] = Footer

; ========================================
; Styles
; ========================================
stylesheets[all][] = css/layouts/home/home.layout.css 
stylesheets[all][] = css/layouts/home/home.layout.no-query.css